### ISSUE TITLE
ERROR WHILE REGISTERING

### ISSUE THREAD

**Issue by fkaris** [clovon/Multipurpose-Laravel-and-Livewire-Application#1]
ERROR BELOW WHEN TRYING TO REGISTER

![Capture](https://user-images.githubusercontent.com/53820798/123918930-0c01e900-d98d-11eb-9a8c-13ff45419ffe.PNG)

**Comment by clovon** [comment]
Thanks. I have fixed this in: 23e8d4b0b27edb88cfe5c97a19be6c89ccd43d67
