### ISSUE TITLE
Message Tabe Errors Showing

### ISSUE THREAD

**Issue by laravelhero** [clovon/Multipurpose-Laravel-and-Livewire-Application#4]
When try to click message tab / menu getting errors

ErrorException
Attempt to read property "receiver" on null (View: D:\laragon\www\adminlte\resources\views\livewire\admin\messages\list-conversation-and-messages.blade.php)

**Comment by hamadaacc** [comment]
yes the same error happened

**Comment by clovon** [comment]
Make sure to verify these two things:
1. Add foreign key constraints on the database level so that you can't delete the user who has a conversation.
2. Make sure your receiver_id on the conversations table exists on the user's table as user ID.
Closing for now. Thanks!
